version: "3"

services:
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: truck
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5430:5432
  web:
    ports:
      - 8082:8082
    build: webapp/.

    depends_on:
      - server
  server:
    build: .
    ports:
      - 8085:8085
    restart: always
    environment:
      DB_NAME: truck
      DB_PWD: test
      DB_USER: test
      DB_HOST: database
      DB_PORT: 5432
      SERVER_HOST: server
      SERVER_PORT: 8085
    depends_on:
      - database
